[package]
name = "rustymon_world"
version = "0.1.0"
edition = "2021"

[features]
binary = ["serde_json", "clap", "reqwest", "tokio", "futures", "rc_protocol", "env_logger"]

[dependencies]
# Used in grid.rs to store intersections on the stack while using a Vec like interface
smallvec = { version = "1.9" }

# Used everywhere for geometry
nalgebra = { version = "0.31", features = ["serde-serialize"] }

# Make the formats serializable
serde = { version = "1.0", features = ["derive"] }
serde_repr = { version = "0.1" } # used in the ...VisualType prototypes

# Used in generator.rs to parse osm's pbf files
libosmium = { version = "0.2.1", path = "../libosmium" }

# Produce json output and read config
serde_json = { version = "1.0", optional = true }

# Cli parsing
clap = { version = "3.2", features = ["derive"], optional = true }

# Publish parsed tiles to the rustymon server
reqwest = { version = "0.11", features = ["json"], optional = true }
tokio = { version = "1.20", features = ["full"], optional = true }
futures = { version = "0.3", optional = true }
rc_protocol = { version = "1.0.0", optional = true }

# Logging
log = { version = "0.4" }
env_logger = { version = "0.9", optional = true }