[package]
name = "rustymon_world"
version = "0.1.0"
edition = "2021"

[dependencies]
smallvec = { version = "1.9" }
nalgebra = { version = "0.31" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
clap = { version = "3.2", features = ["derive"] }
libosmium = { git = "https://github.com/gammelalf/libosmium.git" }