[package]
name = "rustymon_world"
version = "0.1.0"
edition = "2021"

[dependencies]
smallvec = { version = "1.9" }
nalgebra = { version = "0.31" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
serde_repr = { version = "0.1" }
clap = { version = "3.2", features = ["derive"] }
libosmium = { version = "0.2.0" }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.20", features = ["full"] }
futures = { version = "0.3" }
rc_protocol = { version = "1.0.0" }
log = { version = "0.4" }
env_logger = { version = "0.9" }
