[package]
name = "rustymonWorld"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { version = "0.31" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
clap = { version = "3.2", features = ["derive"] }
osmium = { version = "0.1.0", path = "../osmium" }
